spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://(地址)?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: ()
    password: ()

mybatis:
  # 指定实体类包路径
  typeAliasesPackage: com.spring.learn.model.entity
  # 指定xml文件扫描路径
  mapper-locations: classpath:/mapper/**/*.xml