spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-uf6h2s8g5xg6482r75o.mysql.rds.aliyuncs.com:3306/operating-management-20210328?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: opera_man_prod
    password: nengliang2019@

mybatis:
  # 指定实体类包路径
  typeAliasesPackage: com.spring.learn.model.entity
  # 指定xml文件扫描路径
  mapper-locations: classpath:/mapper/**/*.xml